name: Deploy

on:
  push:
    tags:
      - "*"

jobs:
  deploy:
    name: Deploy to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Build and tag Docker image
        run: >-
          export TAG=${${{ github.ref }}##*/}
          echo $TAG
          test $(python3 setup.py --version) == $TAG
          docker build -t ${{ IMG_NAME }}:$TAG .
          docker tag ${{ IMG_NAME }}:$TAG ${{ IMG_NAME }}:latest
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_LOGIN }}" --password-stdin
          docker push ${{ IMG_NAME }}
        env:
          - IMG_NAME: mloncode/mloncode
